version: '3'

services:

    ## Reverse Proxy # # # # # # # # # # # # # # #

    nginx-proxy:
        image: jwilder/nginx-proxy:latest
        ports:
            - ${HTTP_BIND_PORT}:80
            - ${HTTPS_BIND_PORT}:443
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./docker-compose.d/certs:/etc/nginx/certs
            - ./DependentFiles/nginx/my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf


    ## php5.6  # # # # # # # # # # # #
    php56:
        build:
            context: ./DependentFiles/php56
            dockerfile: php56Dockerfile
        hostname: php56.ozn-form
        environment:
            VIRTUAL_HOST: php56.ozn-form.com
            CERT_NAME: ${LOCAL_DOMAIN}
            APACHE_LOG_DIR: "/var/log/apache2"
            TZ: "Asia/Tokyo"
        ports:
            - "20056:22"
        volumes:
            - ./DependentFiles/php56/sites-available:/etc/apache2/sites-available
            - ./DependentFiles/php56/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./DependentFiles/php56/php.ini:/usr/local/etc/php/php.ini
            - ./docker-compose.d/certs:/root/keys
            - ../:/var/www/html


    ## php7.1  # # # # # # # # # # # # # # # #
    php71:
        build:
            context: ./DependentFiles/php7x
            dockerfile: php71Dockerfile
        hostname: php71.ozn-form
        environment:
            VIRTUAL_HOST: php71.ozn-form.com
            CERT_NAME: ${LOCAL_DOMAIN}
            APACHE_LOG_DIR: "/var/log/apache2"
            TZ: "Asia/Tokyo"
        ports:
            - "20071:22"
        volumes:
            - ./DependentFiles/php7x/sites-available:/etc/apache2/sites-available
            - ./DependentFiles/php7x/php71.xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker-compose.d/certs:/root/keys
            - ../:/var/www/html


    ## php7.3  # # # # # # # # # # # # # # # #
    php73:
        build:
            context: ./DependentFiles/php7x
            dockerfile: php73Dockerfile
        hostname: php73.ozn-form
        environment:
            VIRTUAL_HOST: php73.ozn-form.com
            CERT_NAME: ${LOCAL_DOMAIN}
            APACHE_LOG_DIR: "/var/log/apache2"
            TZ: "Asia/Tokyo"
        ports:
            - "20073:22"
        volumes:
            - ./DependentFiles/php7x/sites-available:/etc/apache2/sites-available
            - ./DependentFiles/php7x/php73.xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker-compose.d/certs:/root/keys
            - ../:/var/www/html

    ## php7.4  # # # # # # # # # # # # # # # #
    php74:
        build:
            context: ./DependentFiles/php7x
            dockerfile: php74Dockerfile
        hostname: php74.ozn-form
        environment:
            VIRTUAL_HOST: php74.ozn-form.com
            CERT_NAME: ${LOCAL_DOMAIN}
            APACHE_LOG_DIR: "/var/log/apache2"
            TZ: "Asia/Tokyo"
        ports:
            - "20074:22"
        volumes:
            - ./DependentFiles/php7x/sites-available:/etc/apache2/sites-available
            - ./DependentFiles/php7x/php74.xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker-compose.d/certs:/root/keys
            - ../:/var/www/html

    ##  node.js  # # # # # # # # # # # # # # # #
    node:
        build:
            context: ./DependentFiles/node
            dockerfile: nodeDockerfile
        tty: true
        links:
          - php56:php56.ozn-form.com
          - php71:php71.ozn-form.com
          - php73:php73.ozn-form.com
          - php74:php74.ozn-form.com
        volumes:
          - ..:/root/source:delegated
        working_dir: /root/source

    ##  テスト用 SMTP サーバー  # # # # # # # # # # # # # # # #
    mailhog:
        image: mailhog/mailhog
        ports:
            - "1025:1025"
            - "8025:8025"
